fix: make sure we download and install the proper `oha`
Depending on the detected OS and architecture.

diff --git a/run b/run
--- a/run
+++ b/run
@@ -9,8 +9,16 @@ export TEST_SRC_DIR=${TEST_DIR}/src
 # Detects the operating system.
 case "$(uname -s)" in
 	Linux*)	export DETECTED_OS=linux;;
-	Darwin*) export DETECTED_OS=mac;;
-	CYGWIN*|MINGW*|MSYS*) export DETECTED_OS=windows;;
+	Darwin*) export DETECTED_OS=macos;;
+	#CYGWIN*|MINGW*|MSYS*) export DETECTED_OS=windows;;
+	*) echo -e "${RED}Error: Unsupported OS: $(uname -s)${NORMAL}"; exit 1 ;;
+esac
+
+# Detects the CPU architecture.
+case "$(uname -m)" in
+	x86_64)          export DETECTED_ARCH=amd64;;
+	aarch64|arm64)   export DETECTED_ARCH=arm64;;
+	*) echo -e "${RED}Error: Unsupported architecture: $(uname -m)${NORMAL}"; exit 1 ;;
 esac
 
 if [ -t 1 ] ; then
